
-- GASSIEN Water Reminder — Supabase setup
-- Run this once in Supabase SQL Editor.

create table if not exists public.hydration_settings (
  user_id uuid primary key references auth.users(id) on delete cascade,
  goal_ml integer not null default 2000 check (goal_ml between 500 and 10000),
  interval_minutes integer not null default 60 check (interval_minutes between 15 and 360),
  wake_time time not null default '08:00',
  sleep_time time not null default '23:00',
  language text not null default 'fr' check (language in ('fr','en')),
  updated_at timestamptz not null default now()
);

create table if not exists public.hydration_logs (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  amount_ml integer not null check (amount_ml between 1 and 5000),
  consumed_at timestamptz not null default now(),
  created_at timestamptz not null default now()
);

create index if not exists hydration_logs_user_time_idx on public.hydration_logs(user_id, consumed_at desc);

create table if not exists public.admin_links (
  id bigint generated by default as identity primary key,
  admin_user_id uuid not null references auth.users(id) on delete cascade,
  subject_user_id uuid not null references auth.users(id) on delete cascade,
  unique(admin_user_id, subject_user_id)
);

alter table public.hydration_settings enable row level security;
alter table public.hydration_logs enable row level security;
alter table public.admin_links enable row level security;

revoke all on public.hydration_settings from anon;
revoke all on public.hydration_logs from anon;
revoke all on public.admin_links from anon;

grant select,insert,update on public.hydration_settings to authenticated;
grant select,insert,delete on public.hydration_logs to authenticated;
grant select on public.admin_links to authenticated;

drop policy if exists "settings owner read" on public.hydration_settings;
create policy "settings owner read" on public.hydration_settings for select to authenticated
using (
  user_id = auth.uid()
  or exists(select 1 from public.admin_links al where al.admin_user_id=auth.uid() and al.subject_user_id=hydration_settings.user_id)
);

drop policy if exists "settings owner insert" on public.hydration_settings;
create policy "settings owner insert" on public.hydration_settings for insert to authenticated
with check (user_id = auth.uid());

drop policy if exists "settings owner or admin update" on public.hydration_settings;
create policy "settings owner or admin update" on public.hydration_settings for update to authenticated
using (
  user_id = auth.uid()
  or exists(select 1 from public.admin_links al where al.admin_user_id=auth.uid() and al.subject_user_id=hydration_settings.user_id)
)
with check (
  user_id = auth.uid()
  or exists(select 1 from public.admin_links al where al.admin_user_id=auth.uid() and al.subject_user_id=hydration_settings.user_id)
);

drop policy if exists "logs owner or admin read" on public.hydration_logs;
create policy "logs owner or admin read" on public.hydration_logs for select to authenticated
using (
  user_id = auth.uid()
  or exists(select 1 from public.admin_links al where al.admin_user_id=auth.uid() and al.subject_user_id=hydration_logs.user_id)
);

drop policy if exists "logs owner insert" on public.hydration_logs;
create policy "logs owner insert" on public.hydration_logs for insert to authenticated
with check (user_id = auth.uid());

drop policy if exists "logs owner delete" on public.hydration_logs;
create policy "logs owner delete" on public.hydration_logs for delete to authenticated
using (user_id = auth.uid());

drop policy if exists "admin reads own links" on public.admin_links;
create policy "admin reads own links" on public.admin_links for select to authenticated
using (admin_user_id = auth.uid());

-- Realtime: run once. If a table is already in the publication, Supabase may report that it is already a member; that is harmless.
alter publication supabase_realtime add table public.hydration_settings;
alter publication supabase_realtime add table public.hydration_logs;

-- After BOTH accounts exist, link your admin account to Gassien by replacing the IDs:
-- insert into public.admin_links(admin_user_id, subject_user_id)
-- values ('YOUR_ADMIN_USER_UUID', 'GASSIEN_USER_UUID');
